config/routes.rb
Rails.application.routes.draw do
  root :to => 'businesses#index'

  resources :businesses do
    resources :locations, :except => [:show, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ActiveRecord::Base
  has_many :locations
  validates :business, :presence => true
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :business

  validates :name, :presence => true
  validates :address, :presence => true
  validates :phone, :presence => true
  validates :website, :presence => true
  validates :open, :presence => true
  validates :close, :presence => true
  validates :business_id, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def index
    @businesses = Business.all
    render :index
  end
  def show
    @business = Business.find(params[:id])
    render :show
  end
  def new
    @business = Business.new
    render :new
  end
  def create
    @business = Business.new(business_params)
    if @business.save
      redirect_to  businesses_path
    else
      render :new
    end
  end
  def edit
    @business = Business.find(params[:id])
    render :edit
  end
  def update
    @business= Business.find(params[:id])
    if @business.update(business_params)
      redirect_to businesses_path
    else
      render :edit
    end
  end
  def destroy
    @business = Business.find(params[:id])
    @business.destroy
    redirect_to businesses_path
  end

private
  def business_params
    params.require(:business).permit(:business)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def new
    @business = Business.find(params[:business_id])
    @location = @business.locations.new
  end
  def create
    @business = Business.find(params[:business_id])
    @location = @business.locations.new(location_params)
    if @location.save
      redirect_to business_path(@location.business)
    else
      render :new
    end
  end
  def edit
    @business = Business.find(params[:business_id])
    @location = @business.locations.find(params[:id])
    render :edit
  end

  def update
    @business = Business.find(params[:business_id])
    @location = @business.locations.find(params[:id])
    if @location.update(location_params)
      redirect_to business_path(@location.business)
    else
      render :edit
    end
  end

  def destroy
    @business = Business.find(params[:business_id])
    @location = @business.locations.find(params[:id])
    @location.destroy
    redirect_to business_path(@business)
  end

private
  def location_params
    params.require(:location).permit(:name, :address, :phone, :website, :open, :close)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/businesses/_form.html.erb
<%= render partial: "layouts/errors", locals: { object: @business} %>

<%= form_for @business do |f| %>
  <%= f.label :business %>
  <div class="row">
    <div class="large-6 columns">
      <%= f.text_field :business %>
    </div>
  </div>
  <%= f.submit :class => 'button' %>
<% end %>

app/views/businesses/edit.html.erb
<h1>Edit business</h1>

<%= render "form" %>

app/views/businesses/index.html.erb
<h1>Businesses</h1>

<ul>
  <% @businesses.each do |business| %>
    <li><%= link_to business.business, business_path(business) %></li>
  <% end %>
</ul>

<hr>

<a href="#" data-reveal-id="myModal">Click Me For A Modal</a>

<div id="myModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <h2 id="modalTitle">Awesome. I have it.</h2>
  <p class="lead">Your couch.  It is mine.</p>
  <p>I'm a cool paragraph that lives inside of an even cooler modal. Wins!</p>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>



<%= link_to "New business", new_business_path %>
<script>
$(document).ready(function(){
    var popup = new Foundation.Reveal($('#myModal'));
    popup.open();
});
</script>

app/views/businesses/new.html.erb
<h1>New business</h1>

<%= render "form" %>

app/views/businesses/show.html.erb
<h1><%= @business.business %></h1>

<% if @business.locations.any? %>
  <h4>Here are the locations for this business:</h4>

  <ul>
    <% @business.locations.each do |location| %>
      <li>
        <%= location.name %> |
        <%= location.address %> |
        <%= location.phone %> |
        <%= location.website %> |
        <%= location.open %> |
        <%= location.close %> |
        <%= link_to "Edit", edit_business_location_path(@business, location) %> |
        <%= link_to "Delete", business_location_path(@business, location),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no locations yet!</p>
<% end %>

<p><%= link_to "Add a location", new_business_location_path(@business) %></p>
<p><%= link_to "Delete business", business_path(@business),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to businesses", businesses_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <nav class="top-bar">
        <ul class="title-area">
          <li class="name">
            <h1><%= link_to "WikiStore", businesses_path %></a></h1>
          </li>
        </ul>
        <section class="top-bar-section">
          <ul class="right">
            <li class="divider"></li>
            <li><%= link_to "Business Types", businesses_path %></li>
          </ul>
        </section>
      </nav>
    </header>
    <main>
      <div class="row">
        <div class="small-8 columns"><%= yield %></div>
        <div class="small-4 columns">
          <h2 class="subheader">About WikiStore</h2>
          <p>
            There are places that have stuff. We list those places. If you love stuff you'll love WikiStore.
          </p>
          <br>
          <%= image_tag "businesses.png" %>
        </div>
      </div>
    </main>
    <!-- <footer>
      <div class="wrap row small-up-1 medium-up-3">
        <div class="column">
          <h4>Contact Info</h4>
          <hr>
          <a href="#"><span>Github</span>https://github.com/BullThistle</a>
          <a href="#"><span>Website</span>www.rafamaya.com</a>
        </div>
        <div class="column">
          <h4>Site Map</h4>
          <hr>
          <a href="#">Abous Us</a>
          <a href="#">Services</a>
          <a href="#">Contact Us</a>
        </div>
        <div class="column">
          <h4>Social Media</h4>
          <hr>
          <a href="#">Facebook</a>
          <a href="#">Twitter</a>
          <a href="#">Instagram</a>
        </div>
      </div>
    </footer> -->
  </body>
</html>

app/views/locations/_form.html.erb
<%= render('layouts/errors', :object => @location) %>

<%= form_for [@business, @location] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <%= f.label :website %>
  <%= f.text_field :website %>
  <%= f.label :open %>
  <%= f.text_field :open %>
  <%= f.label :close %>
  <%= f.text_field :close %>
  <p><%= f.submit :class => 'button' %></p>
<% end %>

app/views/locations/edit.html.erb
<h1>Edit Location</h1>

<%= render "form" %>

app/views/locations/new.html.erb
<h1>New location for <%= @business.business %></h1>

<%= render 'form' %>